services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Madrid
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_uca1400_ai_ci
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    networks: [app-net]
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    networks: [app-net]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    env_file:
      - apps/auth/.env
    environment:
      - AUTH_DB_HOST=${DB_HOST}
      - AUTH_DB_PORT=${DB_PORT}
      - AUTH_DB_USER=${DB_USER}
      - AUTH_DB_PASS=${DB_PASSWORD}
      - AUTH_DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - I18N_DIR=/app/dist/libs/common/src/i18n
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "60200:60200"
    volumes:
      - ./certs:/app/certs:ro
    networks: [app-net]
    restart: unless-stopped

  # ---------- Modo depuración ----------
  auth-debug:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: base # usa stage con devDependencies
    container_name: auth-debug
    working_dir: /app
    command: sh -lc "npm ci && npm run start:auth:debug" # --debug 0.0.0.0:9229 --watch
    env_file:
      - apps/auth/.env
    environment:
      - AUTH_DB_HOST=${DB_HOST}
      - AUTH_DB_PORT=${DB_PORT}
      - AUTH_DB_USER=${DB_USER}
      - AUTH_DB_PASS=${DB_PASSWORD}
      - AUTH_DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--enable-source-maps
      - NODE_ENV=development
      - I18N_DIR=/app/libs/common/src/i18n
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "60200:60200" # app
      - "9229:9229" # inspector Node
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
      - auth_node_modules:/app/node_modules
    networks: [app-net]
    profiles: ["debug"] # solo se usa con --profile debug

volumes:
  mariadb-data:
  auth_node_modules:

networks:
  app-net:
    driver: bridge
