module.exports = {
  collectCoverage: true,
  coverageDirectory: '<rootDir>/test/coverage',
  coverageReporters: ['json', 'lcov', 'text', 'clover', 'html'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '\\.spec\\.ts$',
    '/constants/',
    '\\.constants\\.ts$',
    '/enums/',
    '\\.enum\\.ts$',
    '/types/',
    '\\.types?\\.ts$',
    '/interfaces/',
    '\\.interfaces?\\.ts$',
    'dtos?/',
    '\\.dto\\.ts$',
    '/index\\.ts$',
    '\\.spec\\.ts$',
    '\\.test\\.ts$',
    '\\.fixture\\.ts$',
    '\\.mock\\.[jt]s$',
  ],
  projects: ['<rootDir>/apps/auth/test/jest.config.js', '<rootDir>/libs/common/test/jest.config.js'],
};
