module.exports = {
  displayName: 'common',
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '../../..',
  testMatch: ['<rootDir>/libs/common/test/unit/**/*.spec.ts'],
  setupFilesAfterEnv: ['<rootDir>/test/jest.setup.js'],
  moduleNameMapper: {
    '^@common/(.*)$': '<rootDir>/libs/common/src/$1',
    '^@test/(.*)$': '<rootDir>/test/$1',
  },
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/libs/common/tsconfig.json' }],
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '\\.spec\\.ts$',
    '/constants/',
    '\\.constants\\.ts$',
    '/enums/',
    '\\.enum\\.ts$',
    '/types/',
    '\\.types?\\.ts$',
    '/interfaces/',
    '\\.interfaces?\\.ts$',
    'dtos?/',
    '\\.dto\\.ts$',
    '/index\\.ts$',
    '\\.spec\\.ts$',
    '\\.test\\.ts$',
    '\\.fixture\\.ts$',
    '\\.mock\\.[jt]s$',
  ],
};
