-- Crear la base de datos si no existe
CREATE DATABASE IF NOT EXISTS `links_db` DEFAULT CHARACTER
SET
    utf8mb4 DEFAULT COLLATE utf8mb4_uca1400_ai_ci;

USE `links_db`;

-- Crear tabla 'group_links' si no existe
CREATE TABLE
    IF NOT EXISTS `group_links` (
        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `userId` INT UNSIGNED NOT NULL,
        `title` VARCHAR(250) NOT NULL,
        `description` VARCHAR(500) NULL,
        `color` JSON NULL,
        `icon` VARCHAR(250) NULL,
        `parentGroupLinkId` INT UNSIGNED NULL,
        `isFavorite` TINYINT(1) NOT NULL DEFAULT 0,
        `createdAt` DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        `updatedAt` DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        `deletedAt` DATETIME (6) DEFAULT NULL,
        PRIMARY KEY (`id`),
        KEY `IX_group_links_userId` (`userId`),
        KEY `IX_group_links_parentGroupLinkId` (`parentGroupLinkId`),
        CONSTRAINT `FK_group_links_parentGroupLinkId` FOREIGN KEY (`parentGroupLinkId`) REFERENCES `group_links` (`id`) ON DELETE SET NULL
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_uca1400_ai_ci ROW_FORMAT = DYNAMIC;

-- Crear tabla 'links' con buenas prácticas
CREATE TABLE
    IF NOT EXISTS `links` (
        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `userId` INT UNSIGNED NOT NULL,
        `groupLinkId` INT UNSIGNED NULL,
        `url` VARCHAR(2000) NOT NULL,
        `normalizedUrl` VARCHAR(2000) NULL,
        `title` VARCHAR(250) NULL,
        `description` VARCHAR(500) NULL,
        `faviconUrl` VARCHAR(1000) NULL,
        `imagePreviewUrl` VARCHAR(1000) NULL,
        `isFavorite` TINYINT(1) NOT NULL DEFAULT 0,
        `tagList` JSON NULL,
        `isActive` TINYINT(1) NOT NULL DEFAULT 1,
        `lastStatusCode` ENUM('0','200','201','202','204','400','401','403','404','500','503','520') NOT NULL DEFAULT '0',
        `lastCheckedAt` DATETIME(6) NULL,
        `lastVisitedAt` DATETIME(6) NULL,
        `createdAt` DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        `updatedAt` DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        `deletedAt` DATETIME (6) DEFAULT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `UX_links_user_normalizedUrl` (`userId`, `normalizedUrl`),
        KEY `IX_links_userId` (`userId`),
        KEY `IX_links_groupLinkId` (`groupLinkId`),
        KEY `IX_links_isFavorite` (`isFavorite`),
        KEY `IX_links_isActive` (`isActive`),
        CONSTRAINT `FK_links_groupLinkId` FOREIGN KEY (`groupLinkId`) REFERENCES `group_links` (`id`) ON DELETE SET NULL
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_uca1400_ai_ci ROW_FORMAT = DYNAMIC;

USE `links_db`;

-- Insertar grupos de prueba solo si no existen (idempotente)
INSERT IGNORE INTO `group_links` (
    `id`,
    `userId`,
    `title`,
    `description`,
    `color`,
    `icon`,
    `parentGroupLinkId`,
    `isFavorite`,
    `createdAt`
)
VALUES
    (
        1,
        1,
        'Development',
        'Enlaces relacionados con desarrollo de software.',
        '{"r":59,"g":130,"b":246}',
        'code',
        NULL,
        1,
        NOW(6)
    ),
    (
        2,
        1,
        'Design',
        'Recursos de diseño y tipografías.',
        '{"r":236,"g":72,"b":153}',
        'palette',
        NULL,
        0,
        NOW(6)
    ),
    (
        3,
        1,
        'AI & ML',
        'Inteligencia artificial y machine learning.',
        '{"r":139,"g":92,"b":246}',
        'brain',
        NULL,
        1,
        NOW(6)
    ),
    (
        4,
        1,
        'DevOps',
        'Infraestructura, contenedores y despliegue.',
        '{"r":249,"g":115,"b":22}',
        'server',
        NULL,
        0,
        NOW(6)
    ),
    (
        5,
        1,
        'Reading',
        'Artículos y tutoriales para leer.',
        '{"r":16,"g":185,"b":129}',
        'book',
        NULL,
        0,
        NOW(6)
    ),
    (
        6,
        1,
        'Frontend Frameworks',
        'Frameworks de frontend específicos.',
        '{"r":6,"g":182,"b":212}',
        'layout',
        1,
        0,
        NOW(6)
    );

-- Insertar links de prueba solo si no existen (idempotente)
INSERT IGNORE INTO `links` (
    `userId`,
    `groupLinkId`,
    `url`,
    `normalizedUrl`,
    `title`,
    `description`,
    `faviconUrl`,
    `imagePreviewUrl`,
    `isFavorite`,
    `tagList`,
    `isActive`,
    `createdAt`
)
VALUES
    (
        1,
        1,
        'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        'https://developer.mozilla.org/en-us/docs/web/javascript',
        'MDN JavaScript docs',
        'Documentación completa de JavaScript.',
        NULL,
        NULL,
        1,
        '["javascript","docs"]',
        1,
        NOW(6)
    ),
    (
        1,
        NULL,
        'https://news.ycombinator.com/',
        'https://news.ycombinator.com',
        'Hacker News',
        'Noticias de tecnología y startups.',
        NULL,
        NULL,
        0,
        '["tech","news"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://github.com/trending',
        'https://github.com/trending',
        'GitHub Trending',
        'Repositorios más populares del día.',
        NULL,
        NULL,
        0,
        '["github","dev"]',
        1,
        NOW(6)
    ),
    (
        1,
        NULL,
        'https://example.com/?utm_source=twitter',
        'https://example.com',
        'Example',
        'Sitio de ejemplo.',
        NULL,
        NULL,
        0,
        '["test"]',
        1,
        NOW(6)
    ),
    (
        1,
        NULL,
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://www.youtube.com/watch?v=dQw4w9wgxcq',
        'YouTube video',
        'Vídeo de ejemplo.',
        NULL,
        NULL,
        0,
        '["video"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://stackoverflow.com/questions/tagged/nestjs',
        'https://stackoverflow.com/questions/tagged/nestjs',
        'NestJS preguntas',
        'Preguntas recientes de NestJS.',
        NULL,
        NULL,
        0,
        '["nestjs","dev"]',
        1,
        NOW(6)
    ),
    (
        1,
        6,
        'https://nestjs.com/',
        'https://nestjs.com',
        'NestJS',
        'Framework progresivo para Node.',
        NULL,
        NULL,
        1,
        '["nestjs","framework"]',
        1,
        NOW(6)
    ),
    (
        1,
        6,
        'https://react.dev/',
        'https://react.dev',
        'React',
        'Nueva documentación oficial de React.',
        NULL,
        NULL,
        0,
        '["react","frontend"]',
        1,
        NOW(6)
    ),
    (
        1,
        6,
        'https://angular.dev/',
        'https://angular.dev',
        'Angular',
        'Documentación oficial Angular.',
        NULL,
        NULL,
        0,
        '["angular","frontend"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://www.prisma.io/docs',
        'https://www.prisma.io/docs',
        'Prisma docs',
        'Documentación oficial Prisma ORM.',
        NULL,
        NULL,
        0,
        '["orm","prisma"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://www.mysqltutorial.org/',
        'https://www.mysqltutorial.org',
        'MySQL Tutorial',
        'Tutorial completo MySQL.',
        NULL,
        NULL,
        0,
        '["mysql","db"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://www.typescriptlang.org/docs/',
        'https://www.typescriptlang.org/docs',
        'TypeScript Docs',
        'Documentación TS.',
        NULL,
        NULL,
        0,
        '["typescript","dev"]',
        1,
        NOW(6)
    ),
    (
        1,
        5,
        'https://medium.com/tag/programming',
        'https://medium.com/tag/programming',
        'Medium Programming',
        'Artículos sobre programación.',
        NULL,
        NULL,
        0,
        '["programming","articles"]',
        1,
        NOW(6)
    ),
    (
        1,
        5,
        'https://calibre-ebook.com/',
        'https://calibre-ebook.com',
        'Calibre',
        'Gestión de libros electrónicos.',
        NULL,
        NULL,
        0,
        '["ebooks","tools"]',
        1,
        NOW(6)
    ),
    (
        1,
        4,
        'https://www.terraform.io/docs',
        'https://www.terraform.io/docs',
        'Terraform Docs',
        'Documentación oficial Terraform.',
        NULL,
        NULL,
        0,
        '["devops","infra"]',
        1,
        NOW(6)
    ),
    (
        1,
        4,
        'https://hub.docker.com/',
        'https://hub.docker.com',
        'Docker Hub',
        'Contenedores y repositorios Docker.',
        NULL,
        NULL,
        0,
        '["docker","devops"]',
        1,
        NOW(6)
    ),
    (
        1,
        1,
        'https://www.postman.com/',
        'https://www.postman.com',
        'Postman',
        'API Development Platform.',
        NULL,
        NULL,
        0,
        '["api","tools"]',
        1,
        NOW(6)
    ),
    (
        1,
        2,
        'https://www.fontshare.com/',
        'https://www.fontshare.com',
        'Fontshare',
        'Fuentes gratuitas para diseño.',
        NULL,
        NULL,
        0,
        '["design","fonts"]',
        1,
        NOW(6)
    ),
    (
        1,
        3,
        'https://openai.com/',
        'https://openai.com',
        'OpenAI',
        'Inteligencia artificial y modelos.',
        NULL,
        NULL,
        1,
        '["ai","tech"]',
        1,
        NOW(6)
    ),
    (
        1,
        4,
        'https://vercel.com/docs',
        'https://vercel.com/docs',
        'Vercel Docs',
        'Documentación de despliegue serverless.',
        NULL,
        NULL,
        0,
        '["vercel","hosting"]',
        1,
        NOW(6)
    );
