name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (auth)
        run: npm run test:auth | tee reports/junit/auth-test.log

      - name: Run tests (common)
        run: npm run test:common | tee reports/junit/common-test.log

      - name: Run coverage (global)
        run: npm run test:cov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: List test report
        run: ls -lh reports/junit/results.xml || echo "No report found"

      - name: Upload test results (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/junit/results.xml

      - name: Upload Jest logs (auth)
        uses: actions/upload-artifact@v4
        with:
          name: jest-auth-log
          path: reports/junit/auth-test.log

      - name: Upload Jest logs (common)
        uses: actions/upload-artifact@v4
        with:
          name: jest-common-log
          path: reports/junit/common-test.log

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jest Tests
          path: reports/junit/results.xml
          reporter: jest-junit
